spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    username: example@163.com
    password: pwd
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    cache: false

database:
  mysql:
    host: localhost
    port: 3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pwd
    database-name: sls_skin

server:
  port: 8080
yggdrasil:
  database:
    users:
    - email: test1@example.com
      password: 111111
    - email: test2@example.com
      password: 222222
      characters:
      - name: character1
        model: steve
        textures:
          skin: classpath:textures/eromanga/masamune_lzumi.png
          cape: "https://textures.minecraft.net/texture/5786fe99be377dfb6858859f926c4dbc995751e91cee373468c5fbf4865e7151" # Mojang cape
        uploadable-textures:
        - skin
        - cape
    - email: test3@example.com
      password: 333333
      characters:
      - name: character2
        model: alex
        textures:
          skin: classpath:textures/eromanga/elf_yamada.png
      - name: character3
        model: steve
        textures:
          cape: "https://textures.minecraft.net/texture/5786fe99be377dfb6858859f926c4dbc995751e91cee373468c5fbf4865e7151" # Mojang cape
  token:
    time-to-fully-expired: 20m
    enable-time-to-partially-expired: true
    time-to-partially-expired: 10m
    only-last-session-available: false
  core:
    server-name: StarLight-Skin
    url: http://localhost:8080/
    skin-domains:
    - localhost
    login-with-character-name: true
  rate-limit:
    limit-duration: 300ms
    email-limit-duration: 60s
  session:
    auth-expire-time: 15s
