yggdrasil:
  database:
    users:
    - email: test1@to2mbn.org
      password: 111111
    - email: test2@to2mbn.org
      password: 222222
      characters:
      - name: character1
        model: STEVE
        textures:
          SKIN: https:///
          CAPE: https:///
    - email: test3@to2mbn.org
      password: 333333
      characters:
      - name: character2
        model: STEVE
        textures:
          SKIN: https:///
      - name: character3
        model: ALEX
        textures:
          CAPE: https:///
  token:
    time-to-fully-expired: 20m
    enable-time-to-partially-expired: true
    time-to-partially-expired: 10m
    only-last-session-available: false
  core:
    skinDomains:
    - .to2mbn.org
  rate-limit:
    limit-duration: 500ms
