server:
  port: 8080
yggdrasil:
  database:
    users:
    - email: test1@to2mbn.org
      password: 111111
    - email: test2@to2mbn.org
      password: 222222
      characters:
      - name: character1
        model: steve
        textures-locations:
          skin: classpath:textures/eromanga/masamune_lzumi.png
          cape: "https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/5/57/MojangCape2016.png?version=eb4f4be57ef687664299dbef606ec874" # TODO use local texture
    - email: test3@to2mbn.org
      password: 333333
      characters:
      - name: character2
        model: alex
        textures-locations:
          skin: classpath:textures/eromanga/elf_yamada.png
      - name: character3
        model: steve
        textures-locations:
          cape: "https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/5/57/MojangCape2016.png?version=eb4f4be57ef687664299dbef606ec874" # TODO use local texture
  token:
    time-to-fully-expired: 20m
    enable-time-to-partially-expired: true
    time-to-partially-expired: 10m
    only-last-session-available: false
  core:
    server-name: yggdrasil-mock-server
    url: http://localhost:8080/
    skin-domains:
    - localhost
  rate-limit:
    limit-duration: 300ms
  session:
    auth-expire-time: 15s
